language: scala

jdk:
  - oraclejdk8

sudo: false

-env: sbt_version=0.13.17
 jdk: oraclejdk8
 script: ./sbt "^^ ${sbt_version}" compile scripted

-env: sbt_version=1.3.0
 jdk: oraclejdk8
 script: ./sbt ++2.12.6 "^^ ${sbt_version}" compile scripted
